name: Build Git Stargazers app
on:
  push:
    branches:
    - main
    
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Check
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload lint html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [ lint ]
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test

      - name: Upload unit test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  package:
    needs: [ unit-test ]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload generated APK
        uses: actions/upload-artifact@v2
        with:
          name: git-stargazers.apk
          path: app/build/outputs/apk/debug/app-debug.apk