name: Build Git Stargazers app
on:
  push:
    branches:
    - main
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Runt Lint
        run: ./gradlew lintDebug

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html