name: Build Git Stargazers app
on:
  push:
    branches:
    - main
    
jobs:
  build:
    name: deploy to production
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
